import { Box, Group, Paper, Tabs, Text } from '@mantine/core';
import Head from 'next/head';
import { ReactElement } from 'react';
import AppWrapper from '../components/Common/AppWrapper';
import Footer from '../components/Layouts/Footer';
import Intro from '../components/Layouts/Intro';

import CONST_VALUE from '../data/constants';
import { NextPageWithLayout } from '../types';

const Home: NextPageWithLayout = () => {
  return (
    <div>
      <Head>
        <title>{CONST_VALUE.pageTitle.index}</title>
        <meta name="description" content="Generated by Sayanta" />
      </Head>

      <Paper className="min-h-screen w-full rounded-none bg-transparent">
        <main style={{ padding: '0px', maxWidth: '1336px', margin: '0px auto' }}>
            <Intro/>
        </main>
      </Paper>
    </div>
  );
};

Home.getLayout = function getLayout(page: ReactElement) {
  return <AppWrapper>{page}</AppWrapper>;
};

export default Home;
